coverage:
  paths:
    - coverage/.resultset.json

comment:
  if: is_pull_request

summary:
  if: is_pull_request

report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}

diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
