require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'config/**/*'
    - 'spec/spec_helper.rb'
    - !ruby/regexp /old_and_unused\.rb$/
  DisplayCopNames: true
  DisplayStyleGuide: true

Bundler/OrderedGems:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/SpaceBeforeBlockBraces:
  EnforcedStyleForEmptyBraces: space

Metrics/ClassLength:
  Max: 230
  Exclude:
  - 'app/models/invoice_product.rb'

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 19

Metrics/BlockLength:
  Exclude:
   - 'spec/**/*.rb'
   - 'lib/tasks/export_nfes_to_portal.rake'
   - 'lib/tasks/karma.rake'
   - 'lib/tasks/backup_restore.rake'

Style/DateTime:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/LineLength:
  Max: 150

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Max: 118

Metrics/AbcSize:
  Max: 50

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/HeredocDelimiterCase:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/MethodName:
  Enabled: false

Naming/VariableName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
