require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - bin/**/*
    - vendor/bundle/**/*
    - config/**/*
    - spec/spec_helper.rb
    - !ruby/regexp /old_and_unused\.rb$/
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable

Bundler/OrderedGems:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/SpaceBeforeBlockBraces:
  EnforcedStyleForEmptyBraces: space

Layout/LineLength:
  Max: 200

Metrics/ClassLength:
  Max: 230

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 19

Style/ClassAndModuleChildren:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'br_danfe.gemspec'

Metrics/ModuleLength:
  Max: 118

Metrics/AbcSize:
  Max: 50

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/HeredocDelimiterCase:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/MethodName:
  Enabled: false

Naming/VariableName:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/BlockParameterName:
  Enabled: false
