name: Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  linter:
    strategy:
      fail-fast: false # I understand this is to run on all versions.
      matrix:
        ruby: ['3.3.5']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rubocop --display-cop-names --parallel

  rspec:
    strategy:
      fail-fast: false # I understand this is to run on all versions.
      matrix:
        ruby: ['3.3.5']

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      actions: read

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rspec

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage/

      - uses: k1LoW/octocov-action@v1
        if: ${{ !github.event.pull_request.head.repo.fork }}
