name: Tests

on: [push]

jobs:
  linter:
    strategy:
      fail-fast: false # I understand this is to run on all versions.
      matrix:
        ruby: ['3.3.5']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rubocop --display-cop-names --parallel

  rspec:
    strategy:
      fail-fast: false # I understand this is to run on all versions.
      matrix:
        ruby: ['3.3.5']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: |
            curl https://qlty.sh | sh

      - run: |
            bundle exec rspec
            ~/.qlty/bin/qlty coverage publish coverage/coverage.json
        env:
           QLTY_COVERAGE_TOKEN: ${{secrets.QLTY_COVERAGE_TOKEN}}
